services:  
  mqtt-no-auth:
    container_name: mqtt-no-auth
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mounted_volumes/mqtt-no-auth/config/:/mosquitto/config/
  
  mqtt-with-auth:
    container_name: mqtt-with-auth
    image: eclipse-mosquitto:latest
    ports:
      - "51883:1883"
    volumes:
      - ./mounted_volumes/mqtt-with-auth/config/:/mosquitto/config/
