name: mqtt-with-auth
services:
  mqtt-with-auth:
    container_name: mqtt-with-auth
    image: eclipse-mosquitto:latest
    ports:
      - "51883:1883"
    volumes:
      - ./mounted_volumes/mqtt-with-auth/config/:/mosquitto/config/